---
- name: "backuping the folder with configurations"
  hosts: ansible
  become: yes
  become_user: root
  tasks:
    - name: "Ansible going to be backup the folder"
      command: cp -R /home/victor/testing /tmp
    - name: "putting script to 10 seconds sleep"
      command: sleep 15
    - name: "removing the backup directory in /tmp directory"
      file:
        path: /tmp/testing
        state: absent
