---
- name: This is about EC2 instance starting,stopping,Terminating using tags concept
  hosts: localhost
  gather_facts: false
  connection: local
  vars_prompt:
    - name: EC2ID
      prompt: Enter the EC2 instance Id
      private: false
    - name: REGION
      prompt: Enter the region name
      private: false
  tasks:
  - name: Debugging the entered variables in prompt
    debug:
      msg:
        - "The entered instance_id is: {{ EC2ID }}"
        - "The entered region is: {{ REGION }}"
  - name: Sleeping for 5 seconds
    ansible.builtin.pause:
      seconds: 5
  - name: Start the EC2 instance
    ec2:
      instance_ids: "{{ EC2ID }}"
      region: "{{ REGION }}"
      state: running
      wait: yes
    tags:
      - start
      - never
  - name: Stop the EC2 instance
    ec2:
      instance_ids: "{{ EC2ID }}"
      region: "{{ REGION }}"
      state: stopped
      wait: yes
    tags:
      - stop
      - never
  - name: Terminating the EC2 instance
    ec2:
      instance_ids: "{{ EC2ID }}"
      region: "{{ REGION }}"
      state: absent
      wait: yes
    tags:
      - terminate
      - never

## Takeaways:
# By default when you are execute this playbook wouldn't do any tasks, why because in the tag section we specified "never".
# If you wanted to perform a specific task follow the command line below
# ansible-playbook ec2_instance_tags.yml 
# ansible-playbook ec2_instance_tags.yml -t start
# ansible-playbook ec2_instance_tags.yml -t stop
# ansible-playbook ec2_instance_tags.yml -t terminate

