---
- name: ansible-adhoc commands
  hosts: localhost
  tasks:
    - name: Checking whoami
      shell: whoami
      register: whoami_out
    - debug:
        var: whoami_out.stdout_lines
    - name: sleep 3 seconds
      ansible.builtin.pause:
        seconds: 3
    - name: passwd catting
      command: cat /etc/passwd
      register: passwd_out
    - debug:
        var: passwd_out.stdout_lines
    - name: ping and lsblk out
      shell: lsblk
      register: lsblk_out
    - debug:
        var: lsblk_out.stdout_lines
    - name: ping checkouts
      command: ping -c 4 google.com
      register: google_out
    - debug:
        var: google_out.stdout_lines
