---
- name: To find out OS distribution and OS family
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: OS distribution finding
    debug:
      msg:
        - "The OS distribution is: {{ ansible_distribution }}"
        - "The OS name is: {{ ansible_system }}"
        - "The OS family is: {{ ansible_os_family }}"
        - "The OS bash version is: {{ ansible_user_shell }}"
        - "The OS user_directory is: {{ ansible_user_dir }}"
        - "The OS user_id is: {{ ansible_user_id }}"
        - "The OS user_uid is: {{ ansible_user_uid }}"
        - "The OS ansible_python_version is: {{ ansible_python_version }}"
        - "The OS ansible_memory is: {{ ansible_memory_mb }}"
        - "The OS IPV4 is: {{ ansible_default_ipv4 }}"
        - "The OS ansible_dns is: {{ ansible_dns }}"
        - "The OS mount points are: {{ ansible_mounts }}"
