---
- name: hostname with hostvars finding
  hosts: localhost
  gather_facts: yes
  tasks:
  - debug: var=inventory_hostname
  - debug: var=hostvars[inventory_hostname]
  - debug: var=ansible_facts

## Note: By default ansible_facts stored in hostvars. Hence, no need to enable ansible_facts in debug module.
