---
- name: Installing/Uninstalling {{ pkg }}
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
  - name: Install-Uninstall any {{ pkg }} using cmdline variables
    yum:
      name: "{{ pkg }}"
      state: "{{ require_state }}"


### Note: When you execute this playbook, you need to place variable in cmdline example

# ansible-playbook install_uninstall_pkgs.yml -e "pkg=httpd require_state=present"
# ansible-playbook install_uninstall_pkgs.yml -e "pkg=httpd require_state=absent"
# ansible-playbook install_uninstall_pkgs.yml -e "pkg=httpd require_state=latest"
