---
- name: "Checking system uptime"
  hosts: localhost
  become: true
  vars:
    - vedi: Checking system uptime
    - explain: of the remote nodes
  tasks:
  - name: "Intro about the playbook explains in message"
    debug:
      msg: "{{ vedi }},{{ explain }}"

  - name: "Getting the system uptime"
    shell: uptime -p
    register: system_uptime
  - name: "Print uptime of managed nodes"
    debug:
      msg: "{{ system_uptime }}"
