---
- name: Create users through loop
  hosts: localhost
  tasks:
  - name: Delete users
    user:
      name: "{{ item }}"
      state: absent
    with_items: '{{ item }}'
    loop:
      - John
      - sood
      - kane
  - name: User deleted list checkouts
    command: cat /etc/passwd
    register: list_user
  - debug: msg="{{ list_user }}"
