---
- name: Create users thru loop
  hosts: localhost
  become: yes
  vars:
    users: [jerry, ed, john]

  tasks:
  - name: Create users
    user:
      name: '{{ item }}'
    with_items: '{{ users }}'
