---
- name: Create user accounts in Linux
  hosts: localhost
  become: yes
  vars:
    users: [john,ed,emi]
  tasks:
    - name: Create users
      user:
        name: '{{ item }}'
        state: absent
      with_items: '{{ users }}'

    - name: List out the passwd file
      command: cat /etc/passwd
      register: pwd_list
    - debug: msg="{{ pwd_list }}"
