---
- name: This playbook is to feeding the input value in variable already and prompting us to enter the value
  hosts: localhost
  gather_facts: false
  vars:
    my_name: "soandso"
    my_corporatename: "soandso"
  vars_prompt:
    - name: domain
      prompt: Enter the value for domain
      private: false
    - name: username
      prompt: Enter the value of username
      private: false
    - name: password
      prompt: Enter the value for password
      private: yes

  tasks:
  - debug:
      msg:
        - "The value of my_name is: {{ my_name }}"
        - "The value of my_corporatename is: {{ my_corporatename }}"
        - "The value of domain is: {{ domain }}"
        - "The value of username is: {{ username }}"
        - "The value of password is: {{ password }}"
