---
- name: This playbook is to feeding the input value in variable already and prompting us to enter the value
  hosts: localhost
  gather_facts: false
  vars:
    my_name: "thangadurai murugan"
    my_corporatename: "dell.com"
  vars_prompt:
    - name: domain
      prompt: Enter the value for domain
      private: false
    - name: username
      prompt: Enter the value of username
      private: false
    - name: password
      prompt: Enter the value for password
      private: yes
  tasks:
  - debug:
      msg:
        - "Your good name is: {{ my_name }}"
        - "Your working corporatename is: {{ my_corporatename }}"
        - "Your corporate domain is: {{ domain }}"
        - "Your domain username is: {{ username }}"
        - "Your domain password is: {{ password }}"
