---
- name: This playbook is to feeding the input value in variable already and prompting us to enter the value
  hosts: localhost
  gather_facts: false
  vars:
    my_name: "soandso"
    my_wifename: "soandso"
  vars_prompt:
    - name: un
      prompt: Enter the value for un
      private: false
    - name: pw
      prompt: Enter the value of pw
      private: yes

  tasks:
  - debug:
      msg:
        - "The value of my_name is: {{ my_name }}"
        - "The value of my_wifename is: {{ my_wifename }}"
        - "The value of un is: {{ un }}"
        - "The value of pw is: {{ pw }}"
