---
- name: Installing httpd on centOS,amzon2,ubuntu
  become: yes
  gather_facts: yes
  hosts: localhost
  tasks:
  - name: "Installing httpd using {{ ansible_pkg_mgr }}"
    yum:
      name: httpd
      state: present
    when: ansible_distribution != "Ubuntu"
  - name: "Installing apache2 using {{ ansible_pkg_mgr }}"
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"
