---
- name: Simple play to install multiple pkgs
  hosts: dev
  gather_facts: true
  become: yes
  tasks:
    - name: Installing java on RedHat family
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_os_family=="RedHat"
    - name: Installing java on Ubuntu family
      apt:
        name: openjdk-8-jdk
        state: present
      when: ansible_os_family=="Debian"
    - name: Installing websever on REDHAT family
      yum:
        name: httpd
        state: present
      when: ansible_os_family =="RedHat"
    - name: Service starting up
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
    - name: Installing webserver on Ubuntu family
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    - name: Service starting up
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
    - name: Copying index.html on RedHat
      copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_os_family == "RedHat"
    - name: Copying index.html on Ubuntu
      copy:
        src: index.html
        dest: /var/www/html/index.html
      when: ansible_os_family == "Debian"
