---
- name: Checking the disk free on RHEL and CentOS
  hosts: localhost
  tasks:
  - name: Using command or shell module, we can get the disk space util on remote machines
    shell: df -hT
    register: shell_output
  - debug: msg="{{ shell_output }}"
