---
- name: Installing multiple packages
  hosts: dev
  become: yes
  tasks:
  - name: Install begins with the help of Loop
    action: yum name='{{ item }}' state=present
    with_items:
      - git
      - curl
      - java
      - make
