---
- name: "Add several users"
  hosts: localhost
  become: yes
  vars:
    u1: testuser1
    u2: testuser2
  tasks:
  - name: Creating user accounts like "{{ u1, u2 }}"
    user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
    loop:
      - testuser1
      - testuser2
