---
- name: This is about logical operators
  hosts: localhost
  vars:
    x: 5
    y: 6
    z: [4,5,6]
  tasks:
  - name: task will begin now
    debug:
      msg:
        - "x value is: {{ x }} and y value is: {{ y }} and z value is: {{ z }}"
        - "y in z is: {{ y in z }}"
        - "x in z is: {{ x in z }}"
        - "x < y and y >x : {{ x < y and y > x }}"
        - "{{ (4 > 1) and ( 5 < 1) and (1 == 0) }}"
        - "{{ (4 < 5) and ( 5>1 ) and (5 > 2) and (9==0) }}"
        - "{{ (4 < 5) or ( 5>1 ) or (5 > 2) or (9==0) }}"
        - "{{ not (4 >1)}}"
