pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
		stage('Workspace CleanUp'){
		    steps{
			    sh '''
				   echo "Cleaning the Jenkins workspace"
				'''
				cleanWs()
            }
		}
	}
}
