pipeline {
    agent any
	parameters {
        choice choices: ['Development', 'Certification', 'Staging', 'Production'], description: 'Please select the environment?', name: 'ENVIRONMENT'
}
    stages {
        stage('Build') {
            steps {
		echo "The build number is: ${BUILD_NUMBER}"
		echo "The build is happening on: ${ENVIRONMENT}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
		stage('Workspace CleanUp'){
		    steps{
			    sh '''
				   echo "Cleaning the Jenkins workspace"
				   echo "The ${BUILD_NUMBER} workspace is deleted"
				'''
				cleanWs()
            }
		}
	}
}
