---
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: gather ec2 facts
    action: ec2_facts
  - name: install apache on amazon linux ami 2 instances
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"
  - name: install apache on debian or ubuntu instances
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"
