---
  - name: Install and configure tomcat
    hosts: localhost
    gather_facts: false
    become: yes
    vars:
      req_java: java-1.8.0-openjdk
      set_java: jre-1.8.0-openjdk
      req_tomcat_ver: 9.0.70
      tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{ req_tomcat_ver }}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
      tomcat_port: 8090
      war_url: https://github.com/AKSarav/SampleWebApp/raw/master/dist/SampleWebApp.war
    tasks:
    - name: Updating repos
      yum:
        name: "*"
        state: latest
    - name: Installing required java
      yum:
        name: "{{req_java}}"
        state: present
    - name: Setting default java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{set_java}}/bin/java
    - name: Downloading required tomcat
      get_url:
        url: "{{tomcat_url}}"
        dest: /usr/local
    - name: Extracting downloaded tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: Renaming tocmcat home
      command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/apache
    - name: Replacing default port with required port
      template:
        src: server.xml.j2
        dest: /usr/local/apache/conf/server.xml
    - name: Starting tomcat service
      shell:  nohup /usr/local/apache/bin/startup.sh &
    - name: Sleep for 10 seconds
      ansible.builtin.pause:
        seconds: 10
    - name: Stopping tomcat service
      shell: sh /usr/local/apache/bin/shutdown.sh
    - name: Sleep for 5 seconds
      ansible.builtin.pause:
        seconds: 5
    - name: Downloading sample SampleWebApp war file
      get_url:
        url: "{{ war_url }}"
        dest: /usr/local/apache/webapps/SampleWebApp.war
    - name: Starting tomcat service
      shell:  nohup /usr/local/apache/bin/startup.sh &
    - name: Sleep for 5 seconds
      ansible.builtin.pause:
        seconds: 5
    - name: Copying index.html file to /usr/local/apache/
      copy:
        src: index.html
        dest: /usr/local/apache/webapps/SampleWebApp/index.html

