---
- name: Uninstalling MySQLInstall on Remote machines
  hosts: dev
  become: yes
  tasks:
  - name: Remove test user
    mysql_user: name=demo state=absent
  - name: Remove test database
    mysql_db: name=data state=absent
  - name: Remove-MySQL-Python
    yum: name=MySQL-python state=absent
  - name: Stop mysql service
    service: name=mariadb.service state=stopped
  - name: Remove mariadb-server
    command: yum remove -y mariadb-server

