---
- name: "This is about fetching the EC2 instance which are not having tags"
  hosts: localhost
  gather_facts: false
  connection: local
  vars_prompt:
    name: region
    prompt: Enter the region to find out the EC2 instances tagless
    private: false
  tasks:
  - name: Playbook is begin
    ec2_instance_facts:
      region: "{{ region }}"
    register: ec2_info
  - name: Displaying facts
    debug: var=ec2_info
  - name: Sleeping for 10 seconds
    ansible.builtin.pause:
      seconds: 10
  - name: terminating ec2 instances
    ec2:
      region: "{{ region }}"
      instance_ids: "{{ item.instance_id }}"
      state: absent
    with_items: "{{ ec2_info.instances }}"
    when: item.tags.keys() | length ==0

