---
- name: Working on comparison Operators
  hosts: localhost
  vars:
    x: 5
    y: 3
  tasks:
  - name: Playbook begins
    debug:
      msg:
        - "If x == y is: {{ x == y }}"
        - "If x != y is: {{ x != y }}"
        - "If x > y is:  {{ x > y }}"
        - "If x < y is:  {{ x < y }}"
        - "If x >= y is: {{ x >= y }}"
        - "If x <= y is: {{ x <= y }}"
