---
- name: Simple play to understand import_vars and include_vars
  hosts: dev
  gather_facts: true
  tasks:
    - include_vars: required_variables_for_{{ ansible_os_family }}.yml
    - debug:
        msg: "pkg name = {{ pkg }}"
