---
  - name: Updating YUM-APT repo on the remote machines
    hosts: dev
    become: yes
    tasks:
    - name: Update yum
      command: yum update -y
      when: ansible_os_family == "RedHat"
      register: yum_out
    - debug: msg="{{ yum_out }}"
    - name: Sleeping for 5 seconds
      ansible.builtin.pause:
        seconds: 3
    - name: Update apt
      command: apt-get update -y
      when: ansible_os_family == "Debian"
      register: apt_out
    - debug: msg="{{ apt_out }}"
