---
- name: Ping the remote servers
  ping:
  register: ping_out
- debug:
    msg: "{{ ping_out }}"
- name: Find remote machines IP Address
  command: hostname -i
  register: ip_out
- debug:
    msg: "{{ ip_out }}"
- name: Install Apache Webserver on remote machines
  command: yum install -y httpd
  register: install_out
- debug:
    msg: "{{ install_out }}"
- name: Copy custom index.html file to web server directory
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: copy_out
- debug:
    msg: "{{ copy_out }}"
- name: Start Apache Webserver on remote machines
  command: systemctl start httpd
  register: service_out
- debug:
    msg: "{{ service_out }}"

