---
- hosts: web
  become: yes
  become_user: root
  tasks:
   - name: "Updating yum repo"
     shell: yum install -y httpd
   - name: "Starting the httpd serive"
     shell: systemctl start httpd
   - name: "Configured to start at boot the httpd service"
     shell: systemctl enable httpd
   - name: "Copying index.html file"
     copy:
       src: /home/victor/apps/cmx/index.html
       dest: /var/www/html/index.html
   - name: "Restarting httpd service"
     shell: systemctl restart httpd
