---
- hosts: web
  become: yes
  become_user: root
  tasks:
    - name: "Creating an User account in Linux Machines"
      shell: useradd mano
      register: useradd_out
    - debug: msg="{{ useradd_out }}"

    - name: "Checking the user accounts is created or not"
      shell: cat /etc/passwd | grep -i 'mano'
      register: checking_userout
    - debug: msg="{{ checking_userout }}"
