---
- hosts: ansible
  become: yes
  become_user: root
  tasks:
    - name: Install application tree
      yum:
        name: "{{ application_name }}"
        state: "{{ state }}"
        
        
 # Note: while executing this playbook from Ansible control machine to remote machines, follow the steps below
 
 # command to run this playbook ansible-playbook test.yml --extra-vars "application_name=tree state=present"
