---
- name: Installing Multiple packages using Ansible yum Module
  hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: yum packages for CentOS and RHEL
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
    - epel-release
    - git
    - httpd
    - mariadb
    - bind-utils
