---
- name: "launch ec2 instances"
  hosts: localhost
  gather_facts: no
  tasks:
  - ec2:
      region: ap-south-1
      key_name: admin
      instance_type: t2.micro
      image: ami-01216e7612243e0ef
      wait: yes
      count: 1
      vpc_subnet_id: subnet-e9190a81
      assign_public_ip: yes

  - name: displaying output
    debug: msg="{{item.instance_id}}"
    with_items: "{{ec2_info.instances}}"
