---
- name: Creationg of multiple user accounts in Linux box
  hosts: localhost
  gather_facts: True
  become: yes
  tasks:
  - name: User creation is one after another using loop with items
    user:
      name: "{{ item }}"
      state: present
    loop:
      - John
      - David
      - Siju
      - Lijo
      - Aju

  - name: Verifying the user accounts
    command: cat /etc/passwd
    register: user_out
  - debug:
      var: user_out.stdout_lines

  - name: Small break
    ansible.builtin.pause:
      seconds: 5

  - name: Deletion of user accounts along with their /home directories
    user:
      name: "{{ item }}"
      state: absent
      remove: true
    loop:
      - John
      - David
      - Siju
      - Lijo
      - Aju
  - name: Cross verifying the user account status
    command: ls -l /home
    register: cross_out
  - debug:
      var: cross_out.stdout_lines

